/*
 * Author: Neal Su
 * Project Name: Connect Four
 * Description: The GUI component for the project. Includes formatting the JPanel and the JButtons.
 */
package connectfour;

import java.awt.*;
import javax.swing.*;

public class ConnectFour extends javax.swing.JFrame {
    
    // new ConnectFourEvent object
    ConnectFourEvent connectfour = new ConnectFourEvent(this);
    // array of JButtons that simulate the connect 4 board 
    JButton[][] btnArrButton = new JButton[6][7];
    // new JPanel
    JPanel pnlPanel  = new JPanel();
    // static variables to be used in other class
    static JTextArea txtRecord = new JTextArea();
    static JLabel lblTurn = new JLabel();
    static JButton btnReset = new JButton("Reset");
    // empty blanks labels for formatting purposes
    JLabel lblBlank1 = new JLabel();
    JLabel lblBlank2 = new JLabel();
    
        
    /**
     * Creates new form ConnectFour
     */
    public ConnectFour() {
        
        // setting layout
        setSize (800,800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        FlowLayout layout = new FlowLayout();
        setLayout(layout);
        GridLayout layout1 = new GridLayout(7, 7, 0, 0);
        pnlPanel.setLayout(layout1);                
        
        // loop to add each button of the array to the panel 
        for (int x = 0; x < 6; x++)
        {
            for (int y = 0; y < 7; y++)
            {
                btnArrButton [x][y] = new JButton("");
                btnArrButton [x][y].setPreferredSize(new Dimension(100, 100));
                pnlPanel.add(btnArrButton[x][y]);
            }    
        }    
        
        // adding elements to JPanel
        pnlPanel.add(lblBlank1);
        pnlPanel.add(lblBlank2);
        pnlPanel.add(lblTurn);
        pnlPanel.add(btnReset);
        pnlPanel.add(txtRecord);       
        add (pnlPanel);
        
        setVisible(true);
        
        // for loops to add ActionListener to each of the buttons in the array
        for (int x = 0; x < 6; x++)
        {
            for (int y = 0; y < 7; y++)
            {
                btnArrButton[x][y].addActionListener(connectfour);
            }
        } 
        // adds actionListener to reset button as well
        btnReset.addActionListener(connectfour);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConnect4 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConnect4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblConnect4.setText("Welcome to Connect 4!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(lblConnect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(722, Short.MAX_VALUE)
                .addComponent(lblConnect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnectFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnectFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnectFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnectFour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectFour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label lblConnect4;
    // End of variables declaration//GEN-END:variables
}
